# Generated by Django 5.2.3 on 2025-06-22 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/')),
                ('category', models.CharField(choices=[('Politics', 'Politics'), ('Business', 'Business'), ('Technology', 'Technology'), ('Health', 'Health'), ('Science', 'Science'), ('Education', 'Education'), ('Sports', 'Sports'), ('Entertainment', 'Entertainment'), ('World', 'World'), ('Environment', 'Environment'), ('Lifestyle', 'Lifestyle'), ('Travel', 'Travel'), ('Food', 'Food'), ('Crime', 'Crime'), ('Weather', 'Weather'), ('Culture', 'Culture'), ('Opinion', 'Opinion'), ('Breaking', 'Breaking News'), ('Local', 'Local News'), ('Economy', 'Economy')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
